preProcessors:
  git:
    image: alpine
    command:
    - cp
    - -a
    - /home/.
    - /test/
    imports:
      dragon:
        containerPath: /home
        hostPath: d:\Games\Counter Strike 1.6\config
    exports:
      artifacts:
        containerPath: /test
        hostPath: d:\Rie    
