artifacts:
  exportOnCompletion: true
activities:
  git:
    image: godeltech/codereview.tools.gitprovider
    environment:
      GIT_REPOSITORY_URL: https://github.com/GodelTech/CodeReview.Orchestrator.git
      GIT_BRANCH: main
    volumes:
      sources: /src
  cloc:
    image: aldanial/cloc
    volumes:
      sources: /tmp     
    command:
    - --by-file
    - --report-file=/artifacts/stat.cloc.json
    - --json
    - .
  cloc-converter:
    image: godeltech/codereview.file-converter
    volumes:
      sources: /tmp     
    command:
    - cloc
    - --output
    - /artifacts/stat-converted.cloc.json
    - --file
    - /artifacts/stat.cloc.json
    - --prefix
    - ./
  roslyn:
    image: godeltech/codereview.analyzers.roslyn
    environment:
      SOLUTION_FILE_PATH: /src/CodeReview.Orchestrator.sln
    volumes:
      sources: /src
  roslyn-converter:
    image: godeltech/codereview.file-converter
    command:
    - roslyn
    - --output
    - /artifacts/rolsyn-result.zip
    - --folder
    - /artifacts
    - --src
    - /src/
    - --mask
    - '*.roslyn.json'
  evaluator:
    image: godeltech/codereview.evaluator
    command:
    - export-db
    - --output
    - /artifacts/issues.db
    - --folder
    - /artifacts/rolsyn-result.zip
    - --loc
    - /artifacts/stat-converted.cloc.json
