artifacts:
  exportOnCompletion: true
variables: 
  srcPath: /src
activities:
  git:
    image: godeltech/codereview.tools.gitprovider
    environment:
      GIT_REPOSITORY_URL: https://github.com/GodelTech/CodeReview.Orchestrator.git
      GIT_BRANCH: main
    volumes:
      sources: ${var.srcPath}
  roslyn:
    image: godeltech/codereview.analyzers.roslyn
    environment:
      SOLUTION_FILE_PATH: /src/CodeReview.Orchestrator.sln
    volumes:
      sources: ${var.srcPath}
  roslyn-converter:
    image: godeltech/codereview.file-converter
    command:
    - roslyn
    - -o
    - /artifacts/rolsyn-result.zip
    - -f
    - /artifacts
    - -s
    - ${var.srcPath}/
    - -m
    - '*.roslyn.json'
  evaluator:
    image: godeltech/codereview.evaluator
    command:
    - export-db
    - -o
    - /artifacts/issues.db
    - -f
    - /artifacts/rolsyn-result.zip
