artifacts:
  exportOnCompletion: true
variables: 
  srcPath: /src
activities:
  git:
    image: godeltech/codereview.tools.gitprovider
    environment:
      GIT_REPOSITORY_URL: https://github.com/GodelTech/CodeReview.Orchestrator.git
      GIT_BRANCH: main
    volumes:
      sources: ${var.srcPath}
  roslyn:
    image: godeltech/codereview.analyzers.roslyn
    environment:
      SOLUTION_FILE_PATH: /src/CodeReview.Orchestrator.sln
    volumes:
      sources: ${var.srcPath}
  roslyn-converter:
    image: godeltech/codereview.file-converter
    command:
    - roslyn
    - --output
    - /artifacts/rolsyn-result.zip
    - --folder
    - /artifacts
    - --src
    - ${var.srcPath}/
    - --mask
    - '*.roslyn.json'    
  evaluator:
    image: godeltech/codereview.evaluator
    command:
    - evaluate
    - -o
    - /artifacts/evaluation-result.json
    - --manifest
    - /imports/manifest.yaml
    - --folder
    - /artifacts/rolsyn-result.zip
  templater:
    image: godeltech/codereview.template-renderer
    command:
    - evaluate
    - --output
    - /artifacts/result.txt
    - --template
    - /imports/template.liquid
    - --data
    - /artifacts/evaluation-result.json    