volumes:
  artifacts:
    folderToOutput: ./artifacts
    targetFolder: /artifacts
    readOnly: false
  imports:
    targetFolder: /imports
    folderToImport: ./imports
  sources:
    targetFolder: /src
    readOnly: false
variables: 
  srcPath: /src
activities:
  git:
    image: godeltech/codereview.tools.gitprovider
    environment:
      GIT_REPOSITORY_URL: https://github.com/GodelTech/CodeReview.Orchestrator.git
      GIT_BRANCH: main
    volumes:
      sources:
        targetFolder: ${var.srcPath}
  resharper:
    image: godeltech/codereview.analyzers.inspectcode
    environment:
      SOLUTION_FILE_PATH: /src/CodeReview.Orchestrator.sln
    volumes:
      sources:
        targetFolder: ${var.srcPath}
      artifacts:
        targetFolder: /artifacts
  resharper-converter:
    image: godeltech/codereview.file-converter
    command:
    - resharper
    - --output
    - /artifacts/resharper-result.zip
    - --folder
    - /artifacts/result.xml
  evaluator-import-issues:
    image: godeltech/codereview.evaluator
    command:
      - import-issues
      - --output
      - /artifacts/result.db
      - --issues
      - /artifacts/resharper-result.zip
      - --filter
      - /imports/filter.yaml
  evaluator-evaluate:
    image: godeltech/codereview.evaluator
    command:
      - evaluate
      - --output
      - /artifacts/evaluation-result.json
      - --manifest
      - /imports/manifest.yaml
      - --db
      - /artifacts/result.db
  templater:
    image: godeltech/codereview.template-renderer
    command:
    - evaluate
    - --output
    - /artifacts/result.txt
    - --template
    - /imports/template.liquid
    - --data
    - /artifacts/evaluation-result.json        