artifacts:
  exportOnCompletion: true
variables: 
  srcPath: /src
activities:
  git:
    image: godeltech/codereview.tools.gitprovider
    environment:
      GIT_REPOSITORY_URL: https://github.com/GodelTech/CodeReview.Orchestrator.git
      GIT_BRANCH: main
    volumes:
      sources: ${var.srcPath}
  resharper:
    image: godeltech/codereview.analyzers.inspectcode
    environment:
      SOLUTION_FILE_PATH: /src/CodeReview.Orchestrator.sln
    volumes:
      sources: ${var.srcPath}
      artifacts: /artifacts
  resharper-converter:
    image: godeltech/codereview.file-converter
    command:
    - resharper
    - -o
    - /artifacts/resharper-result.zip
    - -f
    - /artifacts/resharper
  evaluator:
    image: godeltech/codereview.evaluator
    command:
    - evaluate
    - -o
    - /artifacts/evaluation-result.json
    - -m
    - /imports/manifest.yaml
    - -f
    - /artifacts/resharper-result.zip
  templater:
    image: godeltech/codereview.template-renderer
    command:
    - evaluate
    - -o
    - /artifacts/result.txt
    - -t
    - /imports/template.liquid
    - -d
    - /artifacts/evaluation-result.json        