artifacts:
  exportOnCompletion: true
variables: 
  srcPath: /src
preProcessors:
  git:
    image: godeltech/codereview.tools.gitprovider
    environment:
      GIT_REPOSITORY_URL: https://github.com/GodelTech/CodeReview.Orchestrator.git
      GIT_BRANCH: main
    volumes:
      sources: ${var.srcPath}
analyzers:
  roslyn:
    image: godeltech/codereview.analyzers.roslyn
    environment:
      SOLUTION_FILE_PATH: /src/CodeReview.Orchestrator.sln
    volumes:
      sources: ${var.srcPath}
postProcessors:
  roslyn-converter:
    image: godeltech/codereview.file-converter
    command:
    - roslyn
    - -o
    - /artifacts/rolsyn-result.zip
    - -f
    - /artifacts/roslyn
    - -s
    - ${var.srcPath}/
  evaluator:
    image: godeltech/codereview.evaluator
    command:
    - evaluate
    - -o
    - /artifacts/evaluation-result.json
    - -m
    - /imports/manifest.yaml
    - -f
    - /artifacts/rolsyn-result.zip
  templater:
    image: godeltech/codereview.template-renderer
    command:
    - evaluate
    - -o
    - /artifacts/result.txt
    - -t
    - /imports/template.liquid
    - -d
    - /artifacts/evaluation-result.json    