queries:
  issueByCategory:
    query: SELECT * FROM Issues WHERE Category = $Category
requests:
  totalIssueCount:
    query: SELECT COUNT(*) FROM Issues
  redundanciesInCode:
    queryRef: issueByCategory
    parameters:
      Category: Redundancies in Code
  topIssue:
    query: SELECT * FROM Issues LIMIT (1)
  issueCountByCategory:
    query: SELECT Category, COUNT(*) AS IssueCount FROM Issues GROUP BY Category

